### ISSUE TITLE
Mounting /app in a docker volume causes issue

### ISSUE THREAD

**Issue by nodje** [papermerge/papermerge-core#207]
Using 2.1.9

trying to mount /app outside of the docker container I get this error:

```
2023-09-19 16:47:56,659 INFO exited: nginx (exit status 1; not expected)
Traceback (most recent call last):
  File "/venv/bin/daphne", line 8, in <module>
2023-09-19 16:47:56,825 INFO gave up: nginx entered FATAL state, too many start retries too quickly
    sys.exit(CommandLineInterface.entrypoint())
  File "/venv/lib/python3.10/site-packages/daphne/cli.py", line 170, in entrypoint
    cls().run(sys.argv[1:])
  File "/venv/lib/python3.10/site-packages/daphne/cli.py", line 232, in run
    application = import_by_path(args.application)
  File "/venv/lib/python3.10/site-packages/daphne/utils.py", line 12, in import_by_path
    target = importlib.import_module(module_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
```

this is odd, I feel it should be working like it does for other containers.
Only the supervisor.log files are created in the container mounted /app folder.

This with a linux mounted fs with root:root 777. It shouldn't be a perm issue. At least supervisor is able to write in it.

My ultimate goal is to run the container as a specific papermerge user a limit the mounted /app folder to this user. But this is not the issue here, it just wouldn't use the folder to create the db or anything it needs to. It fails first on launchong ` ws_server`

**Comment by marfoerst** [comment]
Backlog triage: closing this one out.

This report targets Papermerge 2.x, which was built on Django/daphne. The current 3.x line (now 3.6.0) is a completely different stack — FastAPI + SQLAlchemy — and the code paths referenced here no longer exist, so there is nothing actionable left to fix against the current codebase.

If you are still running into something similar on a current 3.6.x release, please open a fresh issue with your setup and logs and we will take a look. Thanks for the original report, and sorry it sat this long.
