### ISSUE TITLE
Exception when opening the Inbox

### ISSUE THREAD

**Issue by smichaelsen** [papermerge/papermerge-core#257]
In my fresh papermerge 3 installation I added a document to the inbox and it looked fine. Later (I suspect after OCR had finished, but unsure about that) when I opened the inbox again I got this in the browser:

![Screenshot 2023-11-22 at 07 54 46](https://github.com/papermerge/papermerge-core/assets/912435/4d1f76ef-3b50-4b9b-8932-3690c0cebb73)

And `docker logs` says:

```
79.220.xxx.xxx - - [22/Nov/2023:06:54:29 +0000] "GET /api/nodes/2a20e31f-a79b-430e-968a-51bb689cec40?page_number=1&page_size=15&order_by=-title HTTP/1.1" 500 21 "http://49.13.xxx.xxx:12000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0"
Exception in ASGI application
Traceback (most recent call last):
  File "/core_app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/core_app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/core_app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/core_app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/core_app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/core_app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/core_app/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/core_app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/core_app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/core_app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/core_app/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/core_app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/core_app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/core_app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/core_app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    content = await serialize_response(
  File "/core_app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 154, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError

```

**Comment by smichaelsen** [comment]
restarting the docker compose setup did not help

**Comment by ciur** [comment]
Looks like a bug, I will have a look. Thank you for opening a ticket!

**Comment by ciur** [comment]
I cannot reproduce the bug.
Can you help please with more specific step by step description so that I can reproduce it?

I've tried with this docker image: [papermerge/papermerge:3.0dev15](https://hub.docker.com/layers/papermerge/papermerge/3.0dev15/images/sha256-4c3357d0665c619ce2cb7cb6092470342083cfc5f39f887f3e4fe037a1dd4afc)

**Comment by ciur** [comment]
I encountered same issue today. It happens specifically for Inbox folder.
