### ISSUE TITLE
Secret Key not working in Docker and wrong port forwarding

### ISSUE THREAD

**Issue by htc1977** [papermerge/papermerge-core#313]
I just tried to setup a docker stacks environment for papermerge 3.0.2 and faced the following issues:

Not port 80 is used by the web-ui, but port 7000 (not a deal)
```
INFO     Starting server at tcp:port=7000:interface=0.0.0.0
INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO     Configuring endpoint tcp:port=7000:interface=0.0.0.0
INFO     Listening on TCP address 0.0.0.0:7000
```
When trying to access the web-ui, i get an 500 internal server error and see the following exception with a traceback:
```
ERROR    Exception inside application: The SECRET_KEY setting must not be empty.
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/venv/lib/python3.10/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
  File "/venv/lib/python3.10/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
  File "/venv/lib/python3.10/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
  File "/venv/lib/python3.10/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
  File "/venv/lib/python3.10/site-packages/django/contrib/messages/storage/cookie.py", line 77, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
  File "/venv/lib/python3.10/site-packages/django/core/signing.py", line 106, in get_cookie_signer
    key = force_bytes(settings.SECRET_KEY)  # SECRET_KEY may be str or bytes.
  File "/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 95, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```
I tried the environment variables **PAPERMERGE__SECURITY__SECRET_KEY** and **PAPERMERGE__SECRET__SECRET_KEY** as mentioned in https://docs.papermerge.io/3.0/settings/security/, but both don't work.

Any ideas, what could have gone wrong?

Thanks in advanced, Christian.

**Comment by htc1977** [comment]
Using the variable **PAPERMERGE__MAIN__SECRET_KEY** seems to work but now I get a
```
Not Found
The requested resource was not found on this server.
```
page.

**Comment by htc1977** [comment]
wasn't a good idea to use :latest ... after switching to :3.0.2 everything works
