### ISSUE TITLE
Issues while trying to login - relation does not exists

### ISSUE THREAD

**Issue by josedurigon** [papermerge/papermerge-core#499]
This is the docker log

2024-10-22 18:34:02 web-1     | INFO:     127.0.0.1:36768 - "GET /token-validator HTTP/1.0" 401 Unauthorized
2024-10-22 18:34:02 web-1     | INFO 2024-10-22 21:34:02,437 auth Database based authentication for 'john'
2024-10-22 18:34:02 db-1      | 2024-10-22 21:34:02.449 GMT [192] ERROR:  relation "core_user" does not exist at character 312
2024-10-22 18:34:02 db-1      | 2024-10-22 21:34:02.449 GMT [192] STATEMENT:  SELECT core_user.id, core_user.username, core_user.email, core_user.password, core_user.first_name, core_user.last_name, core_user.is_superuser, core_user.is_staff, core_user.is_active, core_user.home_folder_id, core_user.inbox_folder_id, core_user.created_at, core_user.date_joined, core_user.updated_at 
2024-10-22 18:34:02 db-1      | FROM core_user 
2024-10-22 18:34:02 db-1      | WHERE core_user.username = 'john'
2024-10-22 18:34:02 web-1     | 172.19.0.1 - - [22/Oct/2024:21:34:02 +0000] "POST /api/token HTTP/1.1" 500 21 "http://localhost:12000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
2024-10-22 18:34:02 web-1     | Exception in ASGI application
2024-10-22 18:34:02 web-1     | Traceback (most recent call last):
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2024-10-22 18:34:02 web-1     |     result = await app(  # type: ignore[func-returns-value]
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-10-22 18:34:02 web-1     |     return await self.app(scope, receive, send)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
2024-10-22 18:34:02 web-1     |     raise exc from None
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
2024-10-22 18:34:02 web-1     |     await self.app(scope, inner_receive, inner_send)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-10-22 18:34:02 web-1     |     await super().__call__(scope, receive, send)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-10-22 18:34:02 web-1     |     await self.middleware_stack(scope, receive, send)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-10-22 18:34:02 web-1     |     raise exc
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-10-22 18:34:02 web-1     |     await self.app(scope, receive, _send)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-10-22 18:34:02 web-1     |     raise exc
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-10-22 18:34:02 web-1     |     await self.app(scope, receive, sender)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-10-22 18:34:02 web-1     |     await route.handle(scope, receive, send)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-10-22 18:34:02 web-1     |     await self.app(scope, receive, send)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2024-10-22 18:34:02 web-1     |     response = await func(request)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
2024-10-22 18:34:02 web-1     |     raise e
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
2024-10-22 18:34:02 web-1     |     raw_response = await run_endpoint_function(
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-10-22 18:34:02 web-1     |     return await dependant.call(**values)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/auth_server/main.py", line 45, in retrieve_token
2024-10-22 18:34:02 web-1     |     user = await authenticate(db, **kwargs)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/auth_server/auth.py", line 37, in authenticate
2024-10-22 18:34:02 web-1     |     return db_auth(db, username, password)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/auth_server/auth.py", line 106, in db_auth
2024-10-22 18:34:02 web-1     |     user = get_user_by_username(db.get_bind(), username)
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/auth_server/crud.py", line 27, in get_user_by_username
2024-10-22 18:34:02 web-1     |     db_user = session.scalars(stmt).one()
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2420, in scalars
2024-10-22 18:34:02 web-1     |     return self._execute_internal(
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2190, in _execute_internal
2024-10-22 18:34:02 web-1     |     result: Result[Any] = compile_state_cls.orm_execute_statement(
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
2024-10-22 18:34:02 web-1     |     result = conn.execute(
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
2024-10-22 18:34:02 web-1     |     return meth(
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
2024-10-22 18:34:02 web-1     |     return connection._execute_clauseelement(
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
2024-10-22 18:34:02 web-1     |     ret = self._execute_context(
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
2024-10-22 18:34:02 web-1     |     return self._exec_single_context(
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
2024-10-22 18:34:02 web-1     |     self._handle_dbapi_exception(
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
2024-10-22 18:34:02 web-1     |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
2024-10-22 18:34:02 web-1     |     self.dialect.do_execute(
2024-10-22 18:34:02 web-1     |   File "/auth_server_app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
2024-10-22 18:34:02 web-1     |     cursor.execute(statement, parameters)
2024-10-22 18:34:02 web-1     | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "core_user" does not exist
2024-10-22 18:34:02 web-1     | LINE 2: FROM core_user 
2024-10-22 18:34:02 web-1     |              ^
2024-10-22 18:34:02 web-1     | 
2024-10-22 18:34:02 web-1     | [SQL: SELECT core_user.id, core_user.username, core_user.email, core_user.password, core_user.first_name, core_user.last_name, core_user.is_superuser, core_user.is_staff, core_user.is_active, core_user.home_folder_id, core_user.inbox_folder_id, core_user.created_at, core_user.date_joined, core_user.updated_at 
2024-10-22 18:34:02 web-1     | FROM core_user 
2024-10-22 18:34:02 web-1     | WHERE core_user.username = %(username_1)s]
2024-10-22 18:34:02 web-1     | [parameters: {'username_1': 'john'}]
2024-10-22 18:34:02 web-1     | (Background on this error at: https://sqlalche.me/e/20/f405)

it basically says that the relation core_user does not exists

I have used the docker compose instalation with the yml:
  version: "3.9"

  x-backend: &common
    image: papermerge/papermerge:3.0.3
    environment:
        PAPERMERGE__SECURITY__SECRET_KEY: 12345
        PAPERMERGE__AUTH__USERNAME: john
        PAPERMERGE__AUTH__PASSWORD: hohoho
        PAPERMERGE__DATABASE__URL: postgresql://scott:tiger@db:5432/mydatabase
        PAPERMERGE__REDIS__URL: redis://redis:6379/0
    volumes:
      - index_db:/core_app/index_db
      - media:/core_app/media
  services:
    web:
      <<: *common
      ports:
       - "12000:80"
      depends_on:
        - redis
        - db
    worker:
      <<: *common
      command: worker
    redis:
      image: redis:6
    db:
      image: bitnami/postgresql:16.1.0
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        POSTGRESQL_USER: scott
        POSTGRESQL_PASSWORD: tiger
        POSTGRESQL_POSTGRES_PASSWORD: tiger
        POSTGRESQL_DATABASE: mydatabase
  volumes:
    postgres_data:
    index_db:
    media:
    
    Don't know how to proceed here...

**Comment by josedurigon** [comment]
It was the docker version
Nevermind folks
